### ISSUE TITLE
server side?

### ISSUE THREAD

**Issue by BigGitWorld** [ashu12chi/HealthBit#6]
Hi.
I cloned the project and want to run it, but what is HTTP://192.168.43.185:8545 server?
Is this an Ethereum client node and the answer is true, which client do you have used for it?

**Comment by nisiddharth** [comment]
We used [Ganache](https://www.trufflesuite.com/ganache) to create personal Ethereum blockchain for testing.
(After installation run Ganache on Port number 8545, leave other settings at their default.)

Ganache provides simplest one click blockchain, no fancy configuration is required.

**Comment by BigGitWorld** [comment]
thank you.
I saw the ``R.string.ganache`` in the java code!
